const ACTION = {
    REDUX_INIT: '@@redux/INIT',
    SELECT_NODE: 'SELECT_NODE',
    CONNECT_NODE: 'CONNECT_NODE',
    START_DRAWING: 'START_DRAWING',
    STOP_DRAWING: 'STOP_DRAWING',
    REMOVE_NODE: 'REMOVE_NODE',
    REMOVE_ALL_NODE: 'REMOVE_ALL_NODE',
    ADD_CONNECTION: 'ADD_CONNECTION',
    UPDATE_CONNECTIONS: 'UPDATE_CONNECTIONS',
    ADD_NODE: 'ADD_NODE',
    UPDATE_NODE: 'UPDATE_NODE',
    UNDO: 'UNDO',
    REDO: 'REDO'
}

export { ACTION }
